# www.bastelgarage.ch  - purecrea GmbH
# https://www.co2ampel.ch
#
# Sensor:  Sensirion SCD30
#
# Author:  Fabian Affolter
# Date:    2020-12-03
# Version: 0.2-dev
# License: MIT
#
esphome:
  name: co2ampel
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: !secret wifi_ap_ssid
    password: !secret wifi_ap_password

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

web_server:
  port: 80

ota:
  safe_mode: True
  password: !secret ota_password

logger:
  level: DEBUG

i2c:
  sda: D2
  scl: D1
  scan: True
 
sensor:
  - platform: uptime
    name: CO2-Ampel Uptime
  - platform: wifi_signal
    name: "CO2-Ampel WiFi Signal"
    update_interval: 60s
  - platform: adc
    pin: A0
    name: "CO2-Ampel Brightness"
    update_interval: 60s
  - platform: scd30
    co2:
      name: "CO2-Ampel CO2"
      accuracy_decimals: 1
      id: co2

    temperature:
      name: "CO2-Ampel Temperature"
      accuracy_decimals: 2
    humidity:
      name: "CO2-Ampel Humidity"
      accuracy_decimals: 1
    address: 0x61
    update_interval: 5s

binary_sensor:
  - platform: status
    name: "CO2-Ampel Status"
  - platform: gpio
    pin: D3
    name: "CO2-Ampel Button"

light:
  - platform: fastled_clockless
    chipset: WS2811
    pin: D8
    num_leds: 12
    rgb_order: BRG
    id: leds
    name: "CO2-Ampel LEDs"

switch:
  - platform: restart
    name: "CO2-Ampel Restart"
  - platform: template
    name: LEDs
    turn_on_action:
      - light.addressable_set:
          id: leds
          range_from: 4
          range_to: 5
          red: 0%
          green: 100%
          blue: 0%

text_sensor:
  - platform: version
    name: "CO2-Ampel Version"
  - platform: wifi_info
    ip_address:
      name: "CO2-Ampel IP Address"
    mac_address:
      name: "CO2-Ampel MAC Address"