# Wifi
wifi_ssid: The SSID of your WLAN network
wifi_password: The password for your WLAN network

# AP for fall-back
wifi_ap_ssid: co2ampel
wifi_ap_password: co2ampel

# MQTT
mqtt_broker: The IP address of your MQTT broker
mqtt_username: The MQTT username. Use "" for no username
mqtt_password: The MQTT password for the given user. Use "" for no password.
